### ISSUE TITLE
3DGS-mcmc has big effect in scenes with large brightness changes?

### ISSUE THREAD

**Issue by KotaYonezawa** [ubc-vision/3dgs-mcmc#11]
Thanks s lot for great code release!

I tried 3dgs-mcmc with my own dataset. (shot by Insta360 ONE RS 1-inch camera (https://www.insta360.com/jp/product/insta360-oners/1inch-360))
Then, I noticed that 3dgs-mcmc can remove terrible floaters that tends to appear in scenes with large brightness changes.
But I think such effect is not written in the paper.
Does anyone find similar phenomenon?
If possible, I would like to know why such big difference was occurred between vanilla 3dgs and 3dgs-mcmc...

**vanilla 3dgs**
![image-2024-7-1_11-14-56](https://github.com/ubc-vision/3dgs-mcmc/assets/39361859/5d74387a-da9a-4a3f-b092-3f7b8b7a12a4)

https://github.com/ubc-vision/3dgs-mcmc/assets/39361859/d21d1853-b175-4552-abb2-327aa34a298c

**3dgs-mcmc**
![image-2024-7-1_11-14-2](https://github.com/ubc-vision/3dgs-mcmc/assets/39361859/929ccbe3-69d5-4f2e-a074-8e0457376def)

https://github.com/ubc-vision/3dgs-mcmc/assets/39361859/08aa1628-2269-4650-9554-3c390a1f8bad

Note: This scene was shot from road only. (Drone was not used.) So the bridge does not look so good from the side.
(Blue line is camera path.)
![tennoz_fureai_bashi_campath](https://github.com/ubc-vision/3dgs-mcmc/assets/39361859/2c07c003-3f04-4da6-a0c7-d7d9d049b370)

**Comment by yzslab** [comment]
From you video, I think by reducing the [learning rate of `xyz`](https://github.com/graphdeco-inria/gaussian-splatting/blob/472689c0dc70417448fb451bf529ae532d32c095/arguments/__init__.py#L74-L75), or increasing the [densify_grad_threshold](https://github.com/graphdeco-inria/gaussian-splatting/blob/472689c0dc70417448fb451bf529ae532d32c095/arguments/__init__.py#L88), you should be able to get a better result in vanilla 3DGS.

**Comment by KotaYonezawa** [comment]
@yzslab 
Thanks a lot for your great advice!
I tried to change --position_lr_init = 0.000016, then floater was gone with vanilla 3DGS, as you suggested.
(Hmm... it's difficult to search best parameter value...)

**vanilla 3dgs (--position_lr_init = 0.000016)**
![image-2024-7-3_21-41-51](https://github.com/ubc-vision/3dgs-mcmc/assets/39361859/33974fb1-c1c8-4f18-8546-ca5924e6f685)
