### ISSUE TITLE
[Question] Camera poses

### ISSUE THREAD

**Issue by phongnhhn92** [ubc-vision/3dgs-mcmc#13]
Hi,

I have read your paper and I think it produces wonderful results ! I have a question related to the camera poses: Do we strictly have to use sfm (colmap) to estimate camera pose ? Can the method work if we do not have those poses ?

**Comment by shakibakh** [comment]
Hello @phongnhhn92, thank you for the comment. You need to have the camera poses, but they do not necessarily need to be generated using COLMAP.

**Comment by phongnhhn92** [comment]
Thanks for the reply ! I wonder if your method work if I just use identity or random poses ?

**Comment by shakibakh** [comment]
We are not optimizing the camera parameters so it should not work with incorrect poses.

**Comment by phongnhhn92** [comment]
Thanks for the answer !
