### ISSUE TITLE
Metrics from Paper

### ISSUE THREAD

**Issue by fhahlbohm** [ubc-vision/3dgs-mcmc#14]
Hey, big compliment for this project!

I had no problems when installing/running with the provided instructions on Ubuntu 22.04.
For the garden scene I got the following results using a 4090 GPU (training took 40:21):
```
SSIM: 0.8851237
PSNR: 28.1474228
LPIPS: 0.0895511
```

However, when computing the quality metrics I noticed that your evaluation protocol for the paper is using the images obtained by downscaling to the target resolution via PIL's resize function as ground truth (for training and metric computation).

Now here's the issue: The precomputed downscaled images already provided with the Mip-NeRF 360 dataset (e.g., `garden/images_4`) are actually different. More specifically, they are sharper due to the more sophisticated downscaling algorithm used by ImageMagick. This means they are higher quality and thus it is harder to achieve good quality metrics. For papers such as Zip-NeRF and 3DGS, the authors used these "more difficult" images for evaluation.

Now for comparison, here are the metrics I get when comparing the renderings with the images in `garden/images_4`, i.e. the comparison done in Zip-NeRF/3DGS:
```
SSIM: 0.8720605
PSNR: 27.7014008
LPIPS: 0.1009033
```
They are clearly worse, but still better than than those of 3DGS (see original paper). Note that also using the images from `garden/images_4` for training leads to a minor improvement:
```
SSIM: 0.8774610
PSNR: 27.7850628
LPIPS: 0.0955254
```

Thus, I wanted to ask how the 3DGS metrics you show in the paper were computed. Did you simply run the inria code with, e.g., `configs/garden.json`? This would mean that numbers are comparable as then the "easier" images would have been used by both approaches.

**Comment by shakibakh** [comment]
Thank you for your interest in our work and the explanations.
We use the code in this current repo (inria code) to evaluate both 3DGS and our method which I believe uses the default PIL downsampling method (seems to be [bicubic](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.resize)).

**Comment by fhahlbohm** [comment]
That makes sense, thank you!
