### ISSUE TITLE
Question regarding result table in appendix

### ISSUE THREAD

**Issue by cmh1027** [ubc-vision/3dgs-mcmc#15]
![image](https://github.com/user-attachments/assets/38f60cdf-8163-4c12-9917-c229a1d88ba4)
Hello, I'm wondering how you set the experiment setting for random initialization of 3DGS. It states that, for example, garden scene of MipNeRF-360 outputs 27.16 PSNR in random initialization. I followed your instruction in the paper (for random initialization, we follow 3DGS and uniformly random sample 100k Gaussians within three times the extent of the camera bounding box), and it gives only around 25 PSNR. Could you share the baseline experiment code?

**Comment by vvcvv-as** [comment]
Same question. Could u please share the baseline parameters? :)

**Comment by shakibakh** [comment]
Hello. I used 100k Gaussians with the same uniform initialization as provided in[ this code ](https://github.com/ubc-vision/3dgs-mcmc/blob/37cf130180bf3a386cbcadf4c4bce15095bf7e6e/scene/dataset_readers.py#L168). I ran the code again for garden and could get those values. You can also check #14 in case you are testing with a different downsampling method.
