### ISSUE TITLE
Question regarding your diff-gaussian-rasterization changes

### ISSUE THREAD

**Issue by gaetan-landreau** [ubc-vision/3dgs-mcmc#16]
Hi ! 
Thanks a lot first for your work 🤗
I skimmed through the changes you've performed in the rasterization submodule, and I found out that you decided to output another tensor called `is_used ` here: https://github.com/ubc-vision/3dgs-mcmc/blob/a22a24bd7e64b089d983bfcf52c906df7d46f25d/gaussian_renderer/__init__.py#L85

I tried to figured out where such a tensor is used, but I couldn't find anything. Any insights / helps regarding this point ? 

Thanks a lot ! 🙏🏻

**Comment by shakibakh** [comment]
Hello!
Thank you for your comment. is_used was used throughout the development but I didnt use it in the final version. I will remove it from the code to remove the confusion :)
