### ISSUE TITLE
Cannot reproduce NerfSynthetic results

### ISSUE THREAD

**Issue by jkulhanek** [ubc-vision/3dgs-mcmc#19]
Hi, thank you for your nice work!

I'm having issues reproducing the results from the paper on the NerfSynthetic dataset. Here are my results:
https://nerfbaselines.github.io/m-3dgs-mcmc

There are also checkpoints that can be downloaded.
Can you provide the exact commands used to train the method on the dataset?

**Comment by shakibakh** [comment]
@jkulhanek Thank you for your interest in this work.
I just added the config files for all different datasets in configs to reproduce the Table 4 results. I tested a few with the current code and could exactly reproduce those values. Please let me know if you encounter any discrepancy.

**Comment by shakibakh** [comment]
Closing the issue. Please feel free to reopen it if you have any further questions or concerns.

**Comment by shakibakh** [comment]
Closing the issue. Please feel free to reopen it if you have any further questions or concerns.
