### ISSUE TITLE
Results of OMMO dataset are not reproduced

### ISSUE THREAD

**Issue by cmh1027** [ubc-vision/3dgs-mcmc#22]
1. Basically, the code can't deal with OMMO dataset because cameras in the OMMO dataset are RADIAL cameras.
2. Even though I modify the dataset_readers.py code to accept the radial cameras like below,
```
        if intr.model=="SIMPLE_PINHOLE" or intr.model=="SIMPLE_RADIAL":
            focal_length_x = intr.params[0]
            FovY = focal2fov(focal_length_x, height)
            FovX = focal2fov(focal_length_x, width)
        elif intr.model=="PINHOLE" or intr.model=="OPENCV" or intr.model=="RADIAL":
            focal_length_x = intr.params[0]
            focal_length_y = intr.params[1]
            FovY = focal2fov(focal_length_y, height)
            FovX = focal2fov(focal_length_x, width)
 ```
the result is much lower. For example your paper states that metrics of "13" scene is 31.60 / 0.92 / 0.22, my result is 27.81 / 0.86 / 0.22

**Comment by shakibakh** [comment]
We used the data loader in dataset_readers.py for OMMO dataset for both the baseline and our method.

**Comment by cmh1027** [comment]
@shakibakh As mentioned, OMMO dataset from [official website ](https://ommo.luchongshan.com/) contains scenes with radial cameras, so current code gives error in dataset_readers.py. Can I ask what version of OMMO dataset you used? We tried undistorted version of OMMO using COLMAP and now it gives similar results in comparison to the paper.

**Comment by shakibakh** [comment]
@cmh1027 Yes, for OMMO dataset we undistorted it using colmap like in [convert.py](https://github.com/ubc-vision/3dgs-mcmc/blob/main/convert.py).

**Comment by cmh1027** [comment]
@shakibakh Thanks for reply.

**Comment by shakibakh** [comment]
Closing the issue, please feel free to reopen it if you encounter any problem...
