### ISSUE TITLE
about random point

### ISSUE THREAD

**Issue by 2693748650** [ubc-vision/3dgs-mcmc#23]
May I ask how you set up the random point cloud?

**Comment by shakibakh** [comment]
You can find it [here](https://github.com/ubc-vision/3dgs-mcmc/blob/403ee3847e1ba76a2774e787a31ed1aee423ec5d/scene/dataset_readers.py#L168).

**Comment by shakibakh** [comment]
Closing the issue. Please feel free to reopen it if you have any further questions or concerns.
