### ISSUE TITLE
Arguments suggestion for larger scenes

### ISSUE THREAD

**Issue by LaFeuilleMorte** [ubc-vision/3dgs-mcmc#25]
Hi, I'm using a quite big dataset to evaluate MCMC-GS. When I'm using the default config in the paper: scale_reg=0.01, opacity_reg=0.01 in the paper, the results seemed to be very bad and the loss seemed not decrease. After a deeper look into the code. I found that the sampling process tended to produce very large scale gaussians. So I adjust the scale_reg to 0.05. And everything becomes much more normal now, but I still don't know how to set these two regularizations properly.  My scene was took by aerial drones and consists of 973 images, and the initial point cloud has 360, 000 points. Do you have any suggestion on how to adjust my configs. Thank you so much.
Best regards.

**Comment by shakibakh** [comment]
Closing the issue. Please feel free to reopen it if you have any further questions or concerns.

**Comment by shakibakh** [comment]
Closing the issue. Please feel free to reopen it if you have any further questions or concerns.
