### ISSUE TITLE
The reason for different opacity_reg of DB-drjohnson scene?

### ISSUE THREAD

**Issue by cmh1027** [ubc-vision/3dgs-mcmc#26]
Why did you set the value of opacity_reg for drjohnson scene in deep-blending 0.001, not the default value 0.01? I checked that 0.01 gives better result for the scene.

**Comment by shakibakh** [comment]
Yes, 0.01 gives better results. I did experiments with many different seeds, in one case, and in Dr. Johnson scene, it was unable to achieve higher opacity and would fail. So I used 0.001 to ensure this scene always performs well. I think probably a better approach could have been to gradually increase the regularizers.

**Comment by shakibakh** [comment]
Closing the issue. Please feel free to reopen it if you have any further questions or concerns.
