### ISSUE TITLE
utils.cu build error fix in submodules/diff-gaussian-rasterization

### ISSUE THREAD

**Issue by KotaYonezawa** [ubc-vision/3dgs-mcmc#4]
Thanks a lot for great code release!
I could run on Windows 11 PC, and I needed build error fix in utils.cu in submodules/diff-gaussian-rasterization.
I think code should be fixed for convenience.

The error message I faced was as follows.

> C:\Work\3dgs-mcmc\submodules\diff-gaussian-rasterization\cuda_rasterizer\utils.cu(29): error: calling a __host__ function("double  ::sqrt<int, (int)0> (T1)") from a __global__ function("compute_relocation") is not allowed
> C:\Work\3dgs-mcmc\submodules\diff-gaussian-rasterization\cuda_rasterizer\utils.cu(29): error: identifier "sqrt<int, (int)0> " is undefined in device code

I modified following part.

Before modification:
`
float term = (pow(-1, k) / sqrt(k + 1)) * pow(opacity_new[idx], k + 1);
`

After modification: (float cast was added in sqrt())
`
float term = (pow(-1, k) / sqrt((float)(k + 1))) * pow(opacity_new[idx], k + 1);
`

Then I could build diff-gaussian-rasterization successfully.

**Comment by faster-developer** [comment]
I had to replace sqrt with sqrtf.

**Comment by shakibakh** [comment]
The code is only tested on Ubuntu, the specifics are now updated in README.

**Comment by amballa** [comment]
Had the same error building the rasterization submodule. Thanks @KotaYonezawa
