### ISSUE TITLE
math.comb is used in reloc_utils.py but it's not exist in python 3.7.13

### ISSUE THREAD

**Issue by KotaYonezawa** [ubc-vision/3dgs-mcmc#5]
Thanks a lot for great code release!

I tried using Windows PC and I faced following error when I ran train.py.

>   File "C:\Work\3dgs-mcmc\3dgs-mcmc_20240621\utils\reloc_utils.py", line 9, in <module>
>    binoms[n, k] = math.comb(n, k)
> AttributeError: module 'math' has no attribute 'comb'

According to python document, math.comb was added in python 3.8.
But environment.yml specifies that python version is 3.7.13.

I think python version in environment.yml should be modified to newer version, or alternative function same as math.comb should be used in reloc_util.py,
like as follows.

```
def combinations_count(n, k):
    return math.factorial(n) // (math.factorial(n - k) * math.factorial(k))
```

**Comment by faster-developer** [comment]
I used `conda install python=3.8` to upgrade the Python version.

**Comment by shakibakh** [comment]
The code is only tested on Ubuntu, the specifics are now updated in README.

**Comment by NeutrinoLiu** [comment]
specify python=3.8 might lead to some problem when compiling rasterizator, i recommend use scipy.comb as an alternative.
