### ISSUE TITLE
Any reason for the `N_max` selection?

### ISSUE THREAD

**Issue by yzslab** [ubc-vision/3dgs-mcmc#8]
Hi, 
`N_max` is hardcoded to `51`: https://github.com/ubc-vision/3dgs-mcmc/blob/5bf590e58706e32564ee6b30c91a2d12b22566a9/utils/reloc_utils.py#L5-L9
  
But looks like nothing can prevent `N_idx`, which is calculated [here](https://github.com/ubc-vision/3dgs-mcmc/blob/5bf590e58706e32564ee6b30c91a2d12b22566a9/scene/gaussian_model.py#L466) and added 1 [here](https://github.com/ubc-vision/3dgs-mcmc/blob/5bf590e58706e32564ee6b30c91a2d12b22566a9/scene/gaussian_model.py#L452), from being greater than `N_max`. In such a situation, it will lead to an out-of-bound accessing in [cuda rasterizer](https://github.com/shakibakh/diff-gaussian-rasterization/blob/1761eb93b8b9bfebec9fbf06af4654583c2b1ddb/cuda_rasterizer/utils.cu#L28).

**Comment by shakibakh** [comment]
Thanks for reporting this. Seems the clamp was removed when I was cleaning the code, adding it again.
As to why 50, I just chose a large enough value that doesn't cause overflow. In practice, the value of N doesn't really get that high.
